- name: configure
  hosts: 192.168.1.3
  tasks:
    - name: make sure folder exists
      file:
        path: /home/nfs_share
        mode: 0755
        state: directory
	owner: root
	group: root
    - name: enable rpcbind (optional)
      service:
	name: rpcbind
	enabled: yes
    - name: Export file
      template:
	src: ./templates/exports.j2
	dest: /etc/exports
	owner: root
	group: root
	mode: 0644
    - name: change nfs config
      file:
	path: /etc/exports
      register: nfs_conf

    - name: restart service if conf changed
      service:
        name: nfs-server
        state: restarted
      when: nfs_conf.changed
