---
# tasks file for nfs_deploy_server
---
- name: install nfs server
  yum:
    name: nfs-utils
    state: present
- name: configure NFS server
    - name: configure nfs server  
    - include_tasks: configure-nfs.yml

- name: ensure nfs service is enabled and running
  service:
    name: nfs-server
    state: started
    enabled: yes
#  package: name=nfs-utils state=present
